STATISTIC_CATEGORY_HOME = "home"
STATISTIC_CATEGORY_ENCOUNTER = "encounter"
STATISTIC_CATEGORY_MORNING = "morning"
STATISTIC_CATEGORY_EVENING = "evening"
STATISTIC_CATEGORY_RANK = "rank"

NORMAL_STATISTIC_CATEGORIES = [
    STATISTIC_CATEGORY_HOME,
    STATISTIC_CATEGORY_ENCOUNTER,
    STATISTIC_CATEGORY_MORNING,
    STATISTIC_CATEGORY_EVENING,
    STATISTIC_CATEGORY_RANK,
]

STATISTIC_MORNING_START_TIME = 5
STATISTIC_MORNING_END_TIME = 9
STATISTIC_EVENING_START_TIME = 0
STATISTIC_EVENING_END_TIME = 5

STATISTIC_RANK_COUNT = 5

STATISTIC_YEAR_CONFIG = {"2022": [*NORMAL_STATISTIC_CATEGORIES]}
