# Generated by Django 4.0.2 on 2022-02-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_id", models.BigIntegerField(verbose_name="目录ID")),
                (
                    "start_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                ("end_at", models.DateTimeField(null=True, verbose_name="结束时间")),
                ("archived", models.BooleanField(default=False, verbose_name="存档状态")),
            ],
            options={
                "verbose_name": "事项",
                "verbose_name_plural": "事项",
                "db_table": "circle_circle",
                "index_together": {("category_id", "start_at", "end_at")},
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=24, verbose_name="目录名")),
                ("parent_id", models.BigIntegerField(default=0, verbose_name="父级ID")),
                ("creator", models.CharField(max_length=150, verbose_name="创建者")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "目录",
                "verbose_name_plural": "目录",
                "db_table": "circle_category",
                "ordering": ["-create_at"],
                "unique_together": {("name", "parent_id", "creator")},
            },
        ),
    ]
